# -*- coding: utf-8 -*-
"""loss_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGAk67zDHmXQlx07Ksep11NtJZQxa4vz
"""

# loss_utils.py
import torch
import torch.nn.functional as F

class MSEWithAgeContrastive(torch.nn.Module):
    """
    Wrapper loss: MSE + age-guided contrastive loss
    """
    def __init__(self, lambda_m2s=0.2, lambda_s2m=0.2, lambda_m2m=0.2, lambda_s2s=0.1, tau=0.07):
        super().__init__()
        self.lambda_m2s = lambda_m2s
        self.lambda_s2m = lambda_s2m
        self.lambda_m2m = lambda_m2m
        self.lambda_s2s = lambda_s2s
        self.tau = tau
        self.mse = torch.nn.MSELoss()

    def forward(self, age_pred, age_true, mri_emb, snp_emb):
        # === MSE Loss ===
        loss = self.mse(age_pred, age_true)

        # === Normalize embeddings ===
        mri = F.normalize(mri_emb, dim=1)  # (B, D)
        snp = F.normalize(snp_emb, dim=1)  # (B, D)
        B = mri.size(0)

        # === Cosine similarity matrices ===
        sim_m2s = torch.matmul(mri, snp.T)  # MRI->SNP
        sim_s2m = torch.matmul(snp, mri.T)  # SNP->MRI
        sim_m2m = torch.matmul(mri, mri.T)  # MRI->MRI
        sim_s2s = torch.matmul(snp, snp.T)  # SNP->SNP

        # === Age-guided similarity for soft positives ===
        ages = age_true.view(-1, 1)  # (B,1)
        sigma = torch.std(ages) + 1e-12
        age_diff = torch.abs(ages - ages.T)  # (B,B)
        age_sim = torch.exp(-age_diff / sigma)
        age_sim.fill_diagonal_(1.0)  # self-pair=1

        # === Helper: InfoNCE-style loss ===
        def info_nce_loss(sim_matrix, pos_mask):
            logits = sim_matrix / self.tau
            exp_logits = torch.exp(logits)
            pos_term = torch.sum(pos_mask * exp_logits, dim=1)
            all_term = torch.sum(exp_logits, dim=1)
            return -torch.mean(torch.log(pos_term / (all_term + 1e-12)))

        eye_mask = torch.eye(B, device=mri.device)

        # === Hard positive losses ===
        loss_m2s = info_nce_loss(sim_m2s, eye_mask)
        loss_s2m = info_nce_loss(sim_s2m, eye_mask)

        # === Soft age-guided losses ===
        loss_m2m = info_nce_loss(sim_m2m, age_sim)
        loss_s2s = info_nce_loss(sim_s2s, age_sim)

        # === Weighted total ===
        total_cl = (self.lambda_m2s * loss_m2s +
                    self.lambda_s2m * loss_s2m +
                    self.lambda_m2m * loss_m2m +
                    self.lambda_s2s * loss_s2s)

        return loss + total_cl