# -*- coding: utf-8 -*-
"""train_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DX7KEoq3AzSQaGPxm6z_M-9xHXcN9ktg
"""

# train_utils.py
import os
import torch
from torch.utils.data import Dataset
import matplotlib.pyplot as plt

# ---------------- Dataset ----------------
class BrainDataset(Dataset):
    def __init__(self, brains, snps, cas, indices):
        self.brains = brains
        self.snps = snps
        self.cas = cas
        self.indices = indices

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        i = self.indices[idx]
        mri = self.brains[i][None, ...].astype("float32")  # add channel
        snp = self.snps[i].astype("float32")
        ca = self.cas[i].astype("float32")
        return torch.tensor(mri), torch.tensor(snp), torch.tensor(ca)

# ---------------- EarlyStopping ----------------
class EarlyStopping:
    def __init__(self, patience=50, min_delta=0.01):
        self.patience = patience
        self.min_delta = min_delta
        self.best_score = None
        self.counter = 0
        self.early_stop = False

    def __call__(self, val_score):
        if self.best_score is None:
            self.best_score = val_score
        elif val_score > self.best_score - self.min_delta:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = val_score
            self.counter = 0

# ---------------- Save Figures ----------------
def save_fig(train_vals, val_vals, fname, ylabel="MAE", ylim=None):
    plt.plot(train_vals, label="Train")
    plt.plot(val_vals, label="Validation")
    if ylim:
        plt.ylim(ylim)
    plt.ylabel(ylabel)
    plt.xlabel("Epoch")
    plt.legend()
    plt.grid(True)
    plt.savefig(fname)
    plt.close()

def save_mae_fig(history, path):
    save_fig(history["train_mae"], history["val_mae"], path, ylabel="MAE", ylim=(0,20))

def save_loss_fig(history, path):
    save_fig(history["train_loss"], history["val_loss"], path, ylabel="Loss")

# ---------------- Save Checkpoint ----------------
def save_checkpoint(model, optimizer, epoch, save_dir, prefix):
    path = os.path.join(save_dir, f"{prefix}_epoch_{epoch:03d}.pt")
    torch.save({
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict()
    }, path)